In [1]:
import numpy as np
np.arange(start=2, stop=50, step=3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [2]:
import numpy as np
list1=[]
list2=[]
for i in range(5):
    number1 = int(input())
    number2 = int(input())
    list1.append(number1)
    list2.append(number2)
    array1=np.array(list1)
    array2= np.array(list2)
    array3=array1+array2

print(array3)
print(np.sort(array3))


5
2
5
52
5
5
5
5
5
5
[ 7 57 10 10 10]
[ 7 10 10 10 57]


In [3]:
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )
print("No. of dimensions: ", arr.ndim)
print("Size of array: ", arr.size)

No. of dimensions:  2
Size of array:  6


In [4]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [1]:
import numpy as np 
  
a = np.array([[1, 2], 
              [3, 4]]) 
  
b = np.array([[5, 6], 
              [7, 8]]) 
  
# vertical stacking 
print("Vertical stacking:\n", np.vstack((a, b))) 
  
# horizontal stacking 
print("\nHorizontal stacking:\n", np.hstack((a, b)))

Vertical stacking:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal stacking:
 [[1 2 5 6]
 [3 4 7 8]]


In [2]:
import numpy as np
arr=np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18])
print('Original Numpy Array : ' , arr)

uniqueValues, occurCount = np.unique(arr, return_counts=True)
print("Unique Values : " , uniqueValues)
print("Occurrence Count : ", occurCount)

Original Numpy Array :  [11 11 12 13 14 15 16 17 12 13 11 14 18]
Unique Values :  [11 12 13 14 15 16 17 18]
Occurrence Count :  [3 2 2 2 1 1 1 1]
